### ISSUE TITLE
다크모드에서 텍스트가 보이지 않음

### ISSUE THREAD

**Issue by zvuc** [UmaSupporter/umamusume-client#43]
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/2870726/115429872-cca57680-a23e-11eb-9e2e-c302bcb3b169.png">
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/2870726/115429898-d333ee00-a23e-11eb-9921-5b8328cbd5c1.png">

다크모드에서 리스트 배경색이 어둡게 바뀌지 않은 채 텍스트만 흰색이 되어 보이지 않는 문제가 있습니다.

**Comment by riemannulus** [comment]
제보 감사합니다 cc. @JUSTIVE

**Comment by JUSTIVE** [comment]
해당 이슈는 #42 에서 해결되었습니다.
